config/routes.rb
Rails.application.routes.draw do
  resources :holdings
  resources :characters
  resources :domains
  resources :provinces
  resources :regions
  resources :continents
  resources :worlds
  resources :campaigns

end

app/models/world.rb
class World < ActiveRecord::Base
    belongs_to :Campaign
end

app/controllers/worlds_controller.rb
class WorldsController < ApplicationController
  before_action :set_world, only: [:show, :edit, :update, :destroy]

  # GET /worlds
  # GET /worlds.json
  def index
    @worlds = World.all
  end

  # GET /worlds/1
  # GET /worlds/1.json
  def show
  end

  # GET /worlds/new
  def new
    @world = World.new
  end

  # GET /worlds/1/edit
  def edit
  end

  # POST /worlds
  # POST /worlds.json
  def create
    @world = World.new(world_params)

    respond_to do |format|
      if @world.save
        format.html { redirect_to @world, notice: 'World was successfully created.' }
        format.json { render :show, status: :created, location: @world }
      else
        format.html { render :new }
        format.json { render json: @world.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /worlds/1
  # PATCH/PUT /worlds/1.json
  def update
    respond_to do |format|
      if @world.update(world_params)
        format.html { redirect_to @world, notice: 'World was successfully updated.' }
        format.json { render :show, status: :ok, location: @world }
      else
        format.html { render :edit }
        format.json { render json: @world.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /worlds/1
  # DELETE /worlds/1.json
  def destroy
    @world.destroy
    respond_to do |format|
      format.html { redirect_to worlds_url, notice: 'World was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_world
      @world = World.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def world_params
      params.require(:world).permit(:id, :name)
    end
end

app/helpers/worlds_helper.rb
module WorldsHelper
end

app/views/worlds/_form.html.erb
<%= form_for(@world) do |f| %>
  <% if @world.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@world.errors.count, "error") %> prohibited this world from being saved:</h2>

      <ul>
      <% @world.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br>
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/worlds/edit.html.erb
<h1>Editing World</h1>

<%= render 'form' %>

<%= link_to 'Show', @world %> |
<%= link_to 'Back', worlds_path %>

app/views/worlds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Worlds</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @worlds.each do |world| %>
      <tr>
        <td><%= world.id %></td>
        <td><%= world.name %></td>
        <td><%= link_to 'Show', world %></td>
        <td><%= link_to 'Edit', edit_world_path(world) %></td>
        <td><%= link_to 'Destroy', world, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New World', new_world_path %>

app/views/worlds/new.html.erb
<h1>New World</h1>

<%= render 'form' %>

<%= link_to 'Back', worlds_path %>

app/views/worlds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @world.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @world.name %>
</p>

<%= link_to 'Edit', edit_world_path(@world) %> |
<%= link_to 'Back', worlds_path %>