config/routes.rb
Rails.application.routes.draw do
  resources :holdings
  resources :characters
  resources :domains
  resources :provinces
  resources :regions
  resources :continents
  resources :worlds
  resources :campaigns

end

app/models/character.rb
class Character < ActiveRecord::Base
    belongs_to :campaign
    has_one :domain
    has_many :provinces, through: :domain
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: [:show, :edit, :update, :destroy]

  # GET /characters
  # GET /characters.json
  def index
    @characters = Character.all
  end

  # GET /characters/1
  # GET /characters/1.json
  def show
  end

  # GET /characters/new
  def new
    @character = Character.new
  end

  # GET /characters/1/edit
  def edit
  end

  # POST /characters
  # POST /characters.json
  def create
    @character = Character.new(character_params)

    respond_to do |format|
      if @character.save
        format.html { redirect_to @character, notice: 'Character was successfully created.' }
        format.json { render :show, status: :created, location: @character }
      else
        format.html { render :new }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characters/1
  # PATCH/PUT /characters/1.json
  def update
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to @character, notice: 'Character was successfully updated.' }
        format.json { render :show, status: :ok, location: @character }
      else
        format.html { render :edit }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @character.destroy
    respond_to do |format|
      format.html { redirect_to characters_url, notice: 'Character was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character
      @character = Character.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def character_params
      params.require(:character).permit(:id, :name, :abbrevation, :description, :reputation, :alignment, :level_total, :hpmax, :hpcurrent, :strength, :dexterity, :constitution, :intelligence, :wisdom, :charisma, :blood_deriviation_id, :blood_strength, :blood_score, :location_id, :trainedThisRound, :isALieutenant, :isAllowed, :roundsCarriedMaxRP)
    end
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_form.html.erb
<%= form_for(@character) do |f| %>
  <% if @character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
      <% @character.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br>
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :abbrevation %><br>
    <%= f.text_field :abbrevation %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :reputation %><br>
    <%= f.text_field :reputation %>
  </div>
  <div class="field">
    <%= f.label :alignment %><br>
    <%= f.text_field :alignment %>
  </div>
  <div class="field">
    <%= f.label :level_total %><br>
    <%= f.number_field :level_total %>
  </div>
  <div class="field">
    <%= f.label :hpmax %><br>
    <%= f.number_field :hpmax %>
  </div>
  <div class="field">
    <%= f.label :hpcurrent %><br>
    <%= f.number_field :hpcurrent %>
  </div>
  <div class="field">
    <%= f.label :strength %><br>
    <%= f.number_field :strength %>
  </div>
  <div class="field">
    <%= f.label :dexterity %><br>
    <%= f.number_field :dexterity %>
  </div>
  <div class="field">
    <%= f.label :constitution %><br>
    <%= f.number_field :constitution %>
  </div>
  <div class="field">
    <%= f.label :intelligence %><br>
    <%= f.number_field :intelligence %>
  </div>
  <div class="field">
    <%= f.label :wisdom %><br>
    <%= f.number_field :wisdom %>
  </div>
  <div class="field">
    <%= f.label :charisma %><br>
    <%= f.number_field :charisma %>
  </div>
  <div class="field">
    <%= f.label :blood_deriviation_id %><br>
    <%= f.number_field :blood_deriviation_id %>
  </div>
  <div class="field">
    <%= f.label :blood_strength %><br>
    <%= f.number_field :blood_strength %>
  </div>
  <div class="field">
    <%= f.label :blood_score %><br>
    <%= f.number_field :blood_score %>
  </div>
  <div class="field">
    <%= f.label :location_id %><br>
    <%= f.number_field :location_id %>
  </div>
  <div class="field">
    <%= f.label :trainedThisRound %><br>
    <%= f.check_box :trainedThisRound %>
  </div>
  <div class="field">
    <%= f.label :isALieutenant %><br>
    <%= f.check_box :isALieutenant %>
  </div>
  <div class="field">
    <%= f.label :isAllowed %><br>
    <%= f.check_box :isAllowed %>
  </div>
  <div class="field">
    <%= f.label :roundsCarriedMaxRP %><br>
    <%= f.number_field :roundsCarriedMaxRP %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/characters/edit.html.erb
<h1>Editing Character</h1>

<%= render 'form' %>

<%= link_to 'Show', @character %> |
<%= link_to 'Back', characters_path %>

app/views/characters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Characters</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Abbrevation</th>
      <th>Description</th>
      <th>Reputation</th>
      <th>Alignment</th>
      <th>Level total</th>
      <th>Hpmax</th>
      <th>Hpcurrent</th>
      <th>Strength</th>
      <th>Dexterity</th>
      <th>Constitution</th>
      <th>Intelligence</th>
      <th>Wisdom</th>
      <th>Charisma</th>
      <th>Blood deriviation</th>
      <th>Blood strength</th>
      <th>Blood score</th>
      <th>Location</th>
      <th>Trainedthisround</th>
      <th>Isalieutenant</th>
      <th>Isallowed</th>
      <th>Roundscarriedmaxrp</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @characters.each do |character| %>
      <tr>
        <td><%= character.id %></td>
        <td><%= character.name %></td>
        <td><%= character.abbrevation %></td>
        <td><%= character.description %></td>
        <td><%= character.reputation %></td>
        <td><%= character.alignment %></td>
        <td><%= character.level_total %></td>
        <td><%= character.hpmax %></td>
        <td><%= character.hpcurrent %></td>
        <td><%= character.strength %></td>
        <td><%= character.dexterity %></td>
        <td><%= character.constitution %></td>
        <td><%= character.intelligence %></td>
        <td><%= character.wisdom %></td>
        <td><%= character.charisma %></td>
        <td><%= character.blood_deriviation_id %></td>
        <td><%= character.blood_strength %></td>
        <td><%= character.blood_score %></td>
        <td><%= character.location_id %></td>
        <td><%= character.trainedThisRound %></td>
        <td><%= character.isALieutenant %></td>
        <td><%= character.isAllowed %></td>
        <td><%= character.roundsCarriedMaxRP %></td>
        <td><%= link_to 'Show', character %></td>
        <td><%= link_to 'Edit', edit_character_path(character) %></td>
        <td><%= link_to 'Destroy', character, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Character', new_character_path %>

app/views/characters/new.html.erb
<h1>New Character</h1>

<%= render 'form' %>

<%= link_to 'Back', characters_path %>

app/views/characters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @character.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @character.name %>
</p>

<p>
  <strong>Abbrevation:</strong>
  <%= @character.abbrevation %>
</p>

<p>
  <strong>Description:</strong>
  <%= @character.description %>
</p>

<p>
  <strong>Reputation:</strong>
  <%= @character.reputation %>
</p>

<p>
  <strong>Alignment:</strong>
  <%= @character.alignment %>
</p>

<p>
  <strong>Level total:</strong>
  <%= @character.level_total %>
</p>

<p>
  <strong>Hpmax:</strong>
  <%= @character.hpmax %>
</p>

<p>
  <strong>Hpcurrent:</strong>
  <%= @character.hpcurrent %>
</p>

<p>
  <strong>Strength:</strong>
  <%= @character.strength %>
</p>

<p>
  <strong>Dexterity:</strong>
  <%= @character.dexterity %>
</p>

<p>
  <strong>Constitution:</strong>
  <%= @character.constitution %>
</p>

<p>
  <strong>Intelligence:</strong>
  <%= @character.intelligence %>
</p>

<p>
  <strong>Wisdom:</strong>
  <%= @character.wisdom %>
</p>

<p>
  <strong>Charisma:</strong>
  <%= @character.charisma %>
</p>

<p>
  <strong>Blood deriviation:</strong>
  <%= @character.blood_deriviation_id %>
</p>

<p>
  <strong>Blood strength:</strong>
  <%= @character.blood_strength %>
</p>

<p>
  <strong>Blood score:</strong>
  <%= @character.blood_score %>
</p>

<p>
  <strong>Location:</strong>
  <%= @character.location_id %>
</p>

<p>
  <strong>Trainedthisround:</strong>
  <%= @character.trainedThisRound %>
</p>

<p>
  <strong>Isalieutenant:</strong>
  <%= @character.isALieutenant %>
</p>

<p>
  <strong>Isallowed:</strong>
  <%= @character.isAllowed %>
</p>

<p>
  <strong>Roundscarriedmaxrp:</strong>
  <%= @character.roundsCarriedMaxRP %>
</p>

<%= link_to 'Edit', edit_character_path(@character) %> |
<%= link_to 'Back', characters_path %>